spring:
  application:
    name: ng-fields-api

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ng-fields
          audiences: ng-fields-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ng_fields
    driver-class-name: org.postgresql.Driver
    username: ng_fields_user
    password: ${DB_PASSWORD:Pg_ng-fields1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    default-property-inclusion: non_null

server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080
  realm: ng-fields
  admin-client-id: ng-fields-backend
  admin-client-secret: ${KEYCLOAK_CLIENT_SECRET:**********}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.security: INFO
    org.keycloak: INFO
    tg.ngstars: DEBUG
  file:
    path: ./logs

storage:
  upload-dir: ./uploads
  base-url: http://localhost:8081