CREATE TABLE IF NOT EXISTS interventions (
    id UUID PRIMARY KEY,
    reference VARCHAR(255) NOT NULL UNIQUE,
    client_id UUID NOT NULL,
    client_name VARCHAR(255),
    client_email VARCHAR(255),
    client_phone VARCHAR(255),
    client_address VARCHAR(255),
    equipment_type VARCHAR(255),
    equipment_brand VARCHAR(255),
    equipment_model VARCHAR(255),
    equipment_serial VARCHAR(255),
    reported_issue TEXT,
    diagnosis TEXT,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    intervention_date TIMESTAMP WITH TIME ZONE,
    created_by UUID,
    assigned_to UUID,
    site_address VARCHAR(255),
    site_city VARCHAR(255),
    estimated_cost NUMERIC(38,2),
    total_cost NUMERIC(38,2),
    client_signature TEXT,
    technician_signature TEXT,
    signed_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS intervention_items (
    id UUID PRIMARY KEY,
    intervention_id UUID NOT NULL REFERENCES interventions(id),
    type VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(38,2) NOT NULL DEFAULT 0,
    total NUMERIC(38,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
